import inspect
import threading
from collections import OrderedDict
from typing import Optional
from urllib.parse import urljoin

from bs4 import BeautifulSoup

from recipe_scrapers.__version__ import __version__
from recipe_scrapers.settings import settings

from ._exceptions import ElementNotFoundInHtml
from ._grouping_utils import group_ingredients, IngredientGroup
from ._opengraph import OpenGraph
from ._schemaorg import SchemaOrg
from ._videos import best_video_url, find_videos

# Some sites close their content for 'bots', so user-agent must be supplied
HEADERS = {
    "User-Agent": f"Mozilla/5.0 (compatible; Windows NT 10.0; Win64; x64; rv:{__version__}) recipe-scrapers/{__version__}"
}

# Scrapers may be created on several threads at once (see aio.py)
_plugins_lock = threading.Lock()


class AbstractScraper:
    page_data: str

    _opengraph_cls = OpenGraph
    _schema_cls = SchemaOrg

    def __init__(self, html: str, url: str, best_image: Optional[bool] = None):
        self.page_data = html
        self.url = url
        self.soup = BeautifulSoup(self.page_data, "html.parser")
        self.opengraph = self._opengraph_cls(self.soup)
        self.schema = self._schema_cls(self.page_data)
        self.best_image_selection = (
            settings.BEST_IMAGE_SELECTION if best_image is None else bool(best_image)
        )

        # attach the plugins as instructed in settings.PLUGINS
        with _plugins_lock:
            if not hasattr(self.__class__, "plugins_initialized"):
                for name, _ in inspect.getmembers(self, inspect.ismethod):
                    current_method = getattr(self.__class__, name)
                    for plugin in reversed(settings.PLUGINS):
                        if plugin.should_run(self.host(), name):
                            current_method = plugin.run(current_method)
                    setattr(self.__class__, name, current_method)
                setattr(self.__class__, "plugins_initialized", True)

    def author(self):
        """Author of the recipe."""
        raise NotImplementedError("This should be implemented.")

    def canonical_url(self):
        """Canonical or original URL of the recipe."""
        canonical_link = self.soup.find("link", {"rel": "canonical", "href": True})
        if canonical_link:
            return urljoin(self.url, canonical_link["href"])
        return self.url

    def site_name(self):
        """Name of the website."""
        raise NotImplementedError("This should be implemented.")

    @classmethod
    def host(cls) -> str:
        """Host domain of the recipe URL."""
        raise NotImplementedError("This should be implemented.")

    def language(self):
        """Language the recipe is written in."""
        candidate_languages = OrderedDict()
        html = self.soup.find("html", {"lang": True})
        if html:
            candidate_languages[html.get("lang")] = True

        # Deprecated: check for a meta http-equiv header
        # See: https://www.w3.org/International/questions/qa-http-and-lang
        meta_language = self.soup.find(
            "meta",
            {
                "http-equiv": lambda x: x and x.lower() == "content-language",
                "content": True,
            },
        )
        if meta_language:
            language = meta_language.get("content").split(",", 1)[0]
            if language:
                candidate_languages[language] = True

        # If other languages exist, remove 'en' commonly generated by HTML editors
        if len(candidate_languages) > 1:
            candidate_languages.pop("en", None)

        # Return the first candidate language
        if candidate_languages:
            return candidate_languages.popitem(last=False)[0]
        else:
            raise ElementNotFoundInHtml("Could not find language.")

    def title(self):
        """Title of the recipe."""
        raise NotImplementedError("This should be implemented.")

    def ingredients(self):
        """Ingredients of the recipe."""
        raise NotImplementedError("This should be implemented.")

    def ingredient_groups(self) -> list[IngredientGroup]:
        """List of ingredient groups with purpose and ingredients."""
        return group_ingredients(self.ingredients(), self.soup)

    def instructions(self) -> str:
        """Instructions to prepare the recipe."""
        raise NotImplementedError("This should be implemented.")

    def instructions_list(self) -> list[str]:
        """Instructions to prepare the recipe as a list."""
        return [
            instruction
            for instruction in self.instructions().split("\n")
            if instruction
        ]

    def category(self):
        """Category of the recipe."""
        raise NotImplementedError("This should be implemented.")

    def yields(self):
        """Total servings or items in the recipe."""
        raise NotImplementedError("This should be implemented.")

    def description(self):
        """Description of the recipe."""
        raise NotImplementedError("This should be implemented.")

    def total_time(self):
        """Total time needed to prepare and cook the recipe in minutes."""
        raise NotImplementedError("This should be implemented.")

    def cook_time(self):
        """Cooking time in minutes."""
        raise NotImplementedError("This should be implemented.")

    def prep_time(self):
        """Preparation time in minutes."""
        raise NotImplementedError("This should be implemented.")

    def cuisine(self):
        """Cuisine of the recipe."""
        raise NotImplementedError("This should be implemented.")

    def cooking_method(self):
        """The method of cooking the recipe"""
        raise NotImplementedError("This should be implemented.")

    def ratings(self):
        """Ratings of the recipe."""
        raise NotImplementedError("This should be implemented.")

    def ratings_count(self):
        """Total number of ratings of the recipe."""
        raise NotImplementedError("This should be implemented.")

    def equipment(self):
        """Equipment needed for the recipe."""
        raise NotImplementedError("This should be implemented.")

    def nutrients(self):
        """Nutrients of the recipe."""
        raise NotImplementedError("This should be implemented.")

    def dietary_restrictions(self):
        """The specified dietary restrictions or guidelines for which this recipe is suitable"""
        raise NotImplementedError("This should be implemented.")

    def image(self):
        """An image URL for the recipe."""
        raise NotImplementedError("This should be implemented.")

    def keywords(self):
        """Keywords or tags used to describe the recipe"""
        raise NotImplementedError("This should be implemented.")

    def calories(self):
        """Calories per serving as the site states them, e.g. "250 kcal"."""
        calories = self.nutrients().get("calories")
        if not calories:
            raise ElementNotFoundInHtml("calories")
        return calories

    def difficulty(self):
        """How hard the recipe is to make, in the site's own words."""
        raise NotImplementedError("This should be implemented.")

    def reviews(self) -> list[dict[str, str]]:
        """Reviews of the recipe, each with its author, rating, body and date when given."""
        raise NotImplementedError("This should be implemented.")

    def video(self) -> Optional[str]:
        """URL of the recipe's video, or None when the page has none.

        A YouTube watch URL or a media file (.mp4, .m3u8, ...) is preferred, as
        apps can play those as is; otherwise it is the site's embed or page URL.
        """
        return best_video_url(self._videos())

    def videos(self) -> list[dict]:
        """Every video found on the page, the recipe's own first.

        Each has the url to play, content_url, embed_url, thumbnail_url, name,
        duration (in seconds) and upload_date; those the page lacks are None.
        """
        return [video for tier in self._videos() for video in tier]

    def _videos(self):
        return find_videos(self.schema, self.opengraph, self.soup, self.canonical_url())

    def links(self):
        """Links found in the recipe."""
        invalid_href = {"#", ""}
        links_html = self.soup.find_all("a", href=True)

        return [link.attrs for link in links_html if link["href"] not in invalid_href]

    def to_json(self):
        """Recipe information in JSON format."""
        json_dict = {}
        public_method_names = [
            method
            for method in dir(self)
            if callable(getattr(self, method))
            if not method.startswith("_") and method not in ["soup", "links", "to_json"]
        ]
        for method in public_method_names:
            try:
                if method == "ingredient_groups":
                    json_dict[method] = [i.__dict__ for i in getattr(self, method)()]
                else:
                    json_dict[method] = getattr(self, method)()
            except Exception:
                pass
        return json_dict
